server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    io.jwt.primer: DEBUG
  appenders:
    - type: console
      threshold: INFO

swagger:
  resourcePackage: io.jwt.primer.resource
  title: Primer
  description: Low latency & interet scale JWT service

aerospike:
  hosts: "localhost:3000"
  namespace: primer
  maxConnectionsPerNode: 5
  timeout: 1000
  retries: 3
  sleepBetweenRetries: 100

hystrix:
  defaultConfig:
    threadPool:
      timeout: 1000
  commands:
    - name: generate
      threadPool:
        timeout: 200
        concurrency: 4
    - name: disable
      threadPool:
        timeout: 200
        concurrency: 4
    - name: get_dynamic
      threadPool:
        timeout: 100
        concurrency: 4
    - name: generate_static
      threadPool:
        timeout: 200
        concurrency: 4
    - name: disable_static
      threadPool:
        timeout: 200
        concurrency: 4
    - name: get_static
      threadPool:
        timeout: 100
        concurrency: 4
    - name: refresh
      threadPool:
        timeout: 200
        concurrency: 4
    - name: expire
      threadPool:
        timeout: 100
        concurrency: 1
    - name: clear
      threadPool:
        timeout: 100
        concurrency: 4

staticPrivateKey: Z4PWt27w2qkd2DPOHS3iI7PE8xnPPpvP82NDn3C79OeRJCsmmGmRKoNSXTjsqxrv

jwt:
  privateKey: TwhjV5ujkvb41frpmqCve7ZfhqwSDMqOXe01DeDIsb2xCrW4bwfFnax9bi2uC9Kn
  clockSkew: 60
  expiry: 600